### Install the VSCode extension "REST Client"
### (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

@baseUrl = http://localhost:4000
@validGoalId = 60d2200d270fd52c3c975fe4
@validUserId = 60d2176516c0b92be4df5874

### GET all goals
GET {{baseUrl}}/api/goals

### GET a single goal
GET {{baseUrl}}/api/goals/{{validGoalId}}

### GET a not existing goal (404)
GET {{baseUrl}}/api/goals/2000

### POST a new goal
POST http://localhost:4000/api/goals
Content-Type: application/json

{
  "text": "new goal test",
  "isChecked": false,
  "author": "{{validUserId}}"
}

### PATCH a single goal
PATCH {{baseUrl}}/api/goals/{{validGoalId}}
Content-Type: application/json

{
  "text": "goal test 3 updating"
}

### DELETE a single goal
DELETE {{baseUrl}}/api/goals/{{validGoalId}}