### Install the VSCode extension "REST Client"
### (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

@baseUrl = http://localhost:4000
@validUserId = 60d3474b5ba21119570a31d0

@validEmail = deriancastro@hotmail.com

@validPassword = 1234

### GET all users
GET {{baseUrl}}/api/users

### GET a single user
GET {{baseUrl}}/api/users/{{validUserId}}

### GET a non existing user (404)
GET {{baseUrl}}/api/users/2000

### GET - log in a user
GET {{baseUrl}}/api/users/login/{{validEmail}}/{{validPassword}}

### POST a new user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "fullName": "Max Mustermann3",
  "email": "max@muster3.de",
  "password": "1234",
  "aboutYou": "I am a test too",
  "image": "http://res.cloudinary.com/did6rcsck/image/upload/v1625313675/derian-action_lxw5yq.jpg"
}

### PATCH a user
PATCH {{baseUrl}}/api/users/{{validUserId}}
Content-Type: application/json

{
   "fullName": "derian",
   "aboutYou": "I am updating again",
   "image": "http://res.cloudinary.com/did6rcsck/image/upload/v1625313675/derian-action_lxw5yq.jpg"
}

### DELETE a user
DELETE {{baseUrl}}/api/users/{{validUserId}}



