### Install the VSCode extension "REST Client"
### (https://marketplace.visualstudio.com/items?itemName=humao.rest-client)

@baseUrl = http://localhost:4000
@validUserId = 60d3474b5ba21119570a31d0

### GET all users
GET {{baseUrl}}/api/users

### GET a single user
GET {{baseUrl}}/api/users/{{validUserId}}

### GET a non existing user (404)
GET {{baseUrl}}/api/users/2000

### POST a new user
POST http://localhost:4000/api/users
Content-Type: application/json

{
  "fullName": "Max Mustermann",
  "email": "max@muster.de",
  "password": "1234",
  "aboutYou": "I am a test too",
  "image": "http://res.cloudinary.com/did6rcsck/image/upload/v1624372461/IMG_0203_trlmaw.png"
}

### PATCH a user
PATCH {{baseUrl}}/api/users/{{validUserId}}
Content-Type: application/json

{
   "fullName": "deriano",
   "aboutYou": "I am updating again",
   "image": "http://res.cloudinary.com/did6rcsck/image/upload/v1624372461/IMG_0203_trlmaw.png"
}

### DELETE a user
DELETE {{baseUrl}}/api/users/{{validUserId}}